### ISSUE TITLE
Version differs github <--> opscode

### ISSUE THREAD

**Issue by MichaelSp** [yevgenko/cookbook-magento#8]
The version available here http://community.opscode.com/cookbooks/magento does not contain latest fixes in the github.
Can you release a new version, please?

**Comment by yevgenko** [comment]
Hey @MichaelSp, thank you for pointing that out, I'll take care today.

p.s.
feel free to ping me if I forgot ;)

**Comment by yevgenko** [comment]
voila, enjoy! :sunglasses:

**Comment by MichaelSp** [comment]
great, thank you!
